### ISSUE TITLE
MLP cost

### ISSUE THREAD

**Issue by pnvphuong** [karoldvl/paper-2015-esc-convnet#1]
Hi Karol,
In Net-DoubleConv.ipynb file, the MLP cost is defined as the pl2.costs.cost.SumOfCosts of dropout and weightdecay. As I understand, this means the model
- use dropout at every layer
- L2 regularize all weights
  However, it is not mentioned how to minimize the error prediction, e.g. categorical cross entropy.
  Because if cost=None, the MLP will use the default cost function, which maybe the categorical cross entropy loss. However, with the given SumOfCosts , I am not sure how the model reduce the error predictions?

I am new to pylearn2. Thank_ you

**Comment by karolpiczak** [comment]
Closing as this has been addressed separately in an e-mail conversation.
