### ISSUE TITLE
Don't kown how to run the code

### ISSUE THREAD

**Issue by liuhuang31** [karoldvl/paper-2015-esc-convnet#3]
Hi, I read your paper carefully, and downloaded the code, but I am a beginner. i can't run the code,exactly, i don't kown where to start to run.

**Comment by karolpiczak** [comment]
There's a following pipeline built around this codebase:

- Experiment notebooks [`Experiment - ESC-10.ipynb`](https://github.com/karoldvl/paper-2015-esc-convnet/blob/master/Code/Experiment%20-%20ESC-10.ipynb), [`Experiment - ESC-50.ipynb`](https://github.com/karoldvl/paper-2015-esc-convnet/blob/master/Code/Experiment%20-%20ESC-50.ipynb), [`Experiment - UrbanSound8K.ipynb`](https://github.com/karoldvl/paper-2015-esc-convnet/blob/master/Code/Experiment%20-%20UrbanSound8K.ipynb) perform model training and cross-validation on respectively *ESC-10*, *ESC-50* and *UrbanSound8K* datasets.
- After running an experiment notebook, you should get some data in the [`Results/`](https://github.com/karoldvl/paper-2015-esc-convnet/tree/master/Code/Results) (training performance and confusion matrices) and [`_Models/`](https://github.com/karoldvl/paper-2015-esc-convnet/tree/master/Code/_Models) (pickled model weights) directories. You can tweak the `NET_WINDOW_SIZE` and `NET_MODE` variables to get different variants.
- Based on the results you get, you can use the [`Results.ipynb`](https://github.com/karoldvl/paper-2015-esc-convnet/blob/master/Code/Results.ipynb) notebook to summarize it all and generate the final plots.
- If you want/need to delve in,  [`_Datasets/`](https://github.com/karoldvl/paper-2015-esc-convnet/tree/master/Code/_Datasets) has the loading and data preparation/augmentation code for each dataset, while [`_Networks/`](https://github.com/karoldvl/paper-2015-esc-convnet/tree/master/Code/_Networks) has model architecture & training.

One caveat though, this code was originally written around 3 years ago. A lot has happened during this time. Pylearn2 is mostly deprecated, so if you're beginning from scratch, some other machine learning frameworks might be more suitable. I've done a quick [port of this model into Keras](https://github.com/karoldvl/echonet/blob/master/examples/esc_convnet_paper.py) - it may be only a little easier to comprehend (I still think I need to write a *really* minimal working example), but I think it's easier to extend and manipulate.

**Comment by liuhuang31** [comment]
Thank you for your reply and your advice.xixi

**Comment by karolpiczak** [comment]
Sure thing. Closing this one, if you need some additional help, please open a new issue or drop me an e-mail.
