### ISSUE TITLE
 how to get ".pkl, .dat "files

### ISSUE THREAD

**Issue by yyydoing** [karoldvl/paper-2015-esc-convnet#5]
Hello, I read your paper and then read your code, and I would like to re-implement the following code with tensorflow. I would like to run your code first, but I do not know how to get ".pkl, .dat "files, for example: urban_meta.pkl, urban_audio.dat.

**Comment by karolpiczak** [comment]
The `.pkl` and `.dat` files are only for caching purposes to speed things up a bit when rerunning the experiment multiple times. They should get regenerated on first run if they are missing.

**Comment by yyydoing** [comment]
Thank you for the answer, I can not run your code successfully.

**Comment by karolpiczak** [comment]
Could you elaborate a bit more? What errors are you seeing?
