### ISSUE TITLE
Error Running Experiment - UrbanSound8K.ipynb

### ISSUE THREAD

**Issue by yujulucy** [karoldvl/paper-2015-esc-convnet#6]
Hi, I am trying to run the .ipynb file with Jupyter Notebook, but I get the following errors:

In[16]:
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-16-3101bb908f74> in <module>()
----> 1 urban_meta, urban_audio = load_urbansound()
      2 
      3 if os.path.isfile(URBAN_PATH + 'urban_features.pkl'):
      4     urban_features = pd.read_pickle(URBAN_PATH + 'urban_features.pkl')
      5 else:

<ipython-input-16-ccb8511627c3> in load_urbansound()
      7         return rows_meta, rows_audio
      8 
----> 9     metadata = pd.read_csv(URBAN_PATH + 'UrbanSound8K/metadata/UrbanSound8K.csv')
     10 
     11     b = 0

/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.pyc in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, skip_footer, doublequote, delim_whitespace, as_recarray, compact_ints, use_unsigned, low_memory, buffer_lines, memory_map, float_precision)
    644                     skip_blank_lines=skip_blank_lines)
    645 
--> 646         return _read(filepath_or_buffer, kwds)
    647 
    648     parser_f.__name__ = name

/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.pyc in _read(filepath_or_buffer, kwds)
    387 
    388     # Create the parser.
--> 389     parser = TextFileReader(filepath_or_buffer, **kwds)
    390 
    391     if (nrows is not None) and (chunksize is not None):

/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.pyc in __init__(self, f, engine, **kwds)
    728             self.options['has_index_names'] = kwds['has_index_names']
    729 
--> 730         self._make_engine(self.engine)
    731 
    732     def close(self):

/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.pyc in _make_engine(self, engine)
    921     def _make_engine(self, engine='c'):
    922         if engine == 'c':
--> 923             self._engine = CParserWrapper(self.f, **self.options)
    924         else:
    925             if engine == 'python':

/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.pyc in __init__(self, src, **kwds)
   1388         kwds['allow_leading_cols'] = self.index_col is not False
   1389 
-> 1390         self._reader = _parser.TextReader(src, **kwds)
   1391 
   1392         # XXX

pandas/parser.pyx in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4184)()

pandas/parser.pyx in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8449)()

IOError: File /home/jovyan/Datasets/AED/UrbanSound8K/metadata/UrbanSound8K.csv does not exist

In[18]:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-18-d0cc00c35dbe> in <module>()
     12         learning_rate = 0.002
     13 
---> 14     dataset = Dataset(urban_features, fold_testing=TESTING_FOLD, fold_validation=VALIDATION_FOLD, shape=dataset_shape)
     15     model = learn_network(plot_filename='Results/UrbanSound8K-' + NET_WINDOW_SIZE + '-' + NET_MODE + '-Fold_' + str(TESTING_FOLD),
     16                           epochs=epochs, learning_rate=learning_rate)

NameError: name 'urban_features' is not defined

----------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------
May I know what is wrong? And if you have a suggested link to install pylearn2? Thank you.

**Comment by karolpiczak** [comment]
Did you update the `URBAN_PATH = '/home/jovyan/Datasets/AED/'` line in `_Datasets/UrbanSound8K.ipynb` to a correct value?

**pylearn2** should be available from the original repo:
`git clone git://github.com/lisa-lab/pylearn2.git`

**Comment by yujulucy** [comment]
After updating the urban path, I have a few more issues.

In[4]:
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-8-3101bb908f74> in <module>()
----> 1 urban_meta, urban_audio = load_urbansound()
      2 
      3 if os.path.isfile(URBAN_PATH + 'urban_features.pkl'):
      4     urban_features = pd.read_pickle(URBAN_PATH + 'urban_features.pkl')
      5 else:

<ipython-input-6-ccb8511627c3> in load_urbansound()
     20             category_name = row[1]['class']
     21             rows_meta.append(pd.DataFrame({'filename': filename, 'fold': fold, 'category': category, 'category_name': category_name}, index=[0]))
---> 22             rows_audio.append(_load_audio(URBAN_PATH + 'UrbanSound8K/audio/fold{}/{}'.format(fold, filename), 4000))
     23         libc.malloc_trim(0)
     24         b = b + 1

<ipython-input-6-a1a21082c805> in _load_audio(path, duration)
      1 def _load_audio(path, duration):
      2     audio = pydub.AudioSegment.silent(duration=duration)
----> 3     audio = audio.overlay(pydub.AudioSegment.from_file(path).set_frame_rate(22050).set_channels(1))[0:duration]
      4     raw = (np.fromstring(audio._data, dtype="int16") + 0.5) / (0x7FFF + 0.5)   # convert to float
      5     return raw

/usr/local/lib/python2.7/dist-packages/pydub/audio_segment.pyc in from_file(cls, file, format, codec, parameters, **kwargs)
    509             raise CouldntDecodeError("Decoding failed. ffmpeg returned error code: {0}\n\nOutput from ffmpeg/avlib:\n\n{1}".format(p.returncode, p_err))
    510 
--> 511         obj = cls._from_safe_wav(output)
    512 
    513         input_file.close()

/usr/local/lib/python2.7/dist-packages/pydub/audio_segment.pyc in _from_safe_wav(cls, file)
    542         file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
    543         file.seek(0)
--> 544         return cls(data=file)
    545 
    546     def export(self, out_f=None, format='mp3', codec=None, bitrate=None, parameters=None, tags=None, id3v2_version='4', cover=None):

/usr/local/lib/python2.7/dist-packages/pydub/audio_segment.pyc in __init__(self, data, *args, **kwargs)
    153                 data = d
    154 
--> 155             raw = wave.open(StringIO(data), 'rb')
    156 
    157             raw.rewind()

/usr/lib/python2.7/wave.pyc in open(f, mode)
    509             mode = 'rb'
    510     if mode in ('r', 'rb'):
--> 511         return Wave_read(f)
    512     elif mode in ('w', 'wb'):
    513         return Wave_write(f)

/usr/lib/python2.7/wave.pyc in __init__(self, f)
    162         # else, assume it is an open file object already
    163         try:
--> 164             self.initfp(f)
    165         except:
    166             if self._i_opened_the_file:

/usr/lib/python2.7/wave.pyc in initfp(self, file)
    142             chunkname = chunk.getname()
    143             if chunkname == 'fmt ':
--> 144                 self._read_fmt_chunk(chunk)
    145                 self._fmt_chunk_read = 1
    146             elif chunkname == 'data':

/usr/lib/python2.7/wave.pyc in _read_fmt_chunk(self, chunk)
    272             self._sampwidth = (sampwidth + 7) // 8
    273         else:
--> 274             raise Error, 'unknown format: %r' % (wFormatTag,)
    275         self._framesize = self._nchannels * self._sampwidth
    276         self._comptype = 'NONE'

Error: unknown format: 65534
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Is this due to frame rate of the dataset? But I am using the original UrbanSound8k dataset.

I do not seem to have the urban_features.pkl after running the code as well.

**Comment by karolpiczak** [comment]
Are you sure you have the proper version of the dataset? See https://github.com/jiaaro/pydub/issues/129

Downsampling with ffmpeg/sox should help.

**Comment by yujulucy** [comment]
I will look into it!
