### ISSUE TITLE
the issue about the number of frames

### ISSUE THREAD

**Issue by carrie1995-xu** [karoldvl/paper-2015-esc-convnet#8]
hello!
I have read paper'ENVIRONMENTAL SOUND CLASSIFICATION WITH CONVOLUTIONAL NEURAL NETWORKS',but I am confused of a detail:the frames' number  of dataset is 41,why is 41?I calculate the frames by formula,at the same time I implement it by python librosa.I used the same parameters with you(same sr,hop_lengh,window size),but i got different frames number....
could you kindly explain the frames meaning and how to calculate it to me?It's very import for me.
Thank you very much. I am looking forward to  early reply!

**Comment by karolpiczak** [comment]
The frame number is set arbitrarily. As I recall I was aiming at 40 frames for short variant, but some processing stuff I missed resulted in one more frame, so in the end it was 41.

Maybe some of the information on another issue could be helpful:
https://github.com/karolpiczak/paper-2015-esc-convnet/issues/4

**Comment by carrie1995-xu** [comment]
Thank you very much for your answer!
